### ISSUE TITLE
Raw html support

### ISSUE THREAD

**Issue by Rogue-14** [tonybaloney/sphinxcontrib-confluencebuilder#168] opened 2019-01-14 15:03 UTC
With an RST like this:
```
Report
======

.. raw:: html
    :file: generated/report.html
```

I get this error: WARNING: error reading file C:\\repo\\docs\\_build\\html\\report.conf: [Errno 2] No such file or directory: 'C:\\repos\\docs\\_build\\html\\report.conf' 

This works just fine for the html target. How am I supposed to include a raw html file for confluence publishing? Using the "confluence" target makes the error go away, but then it assumes it's in the confluence storage format, and it's obviously not.

**Comment by jdknight** [comment] 2019-01-16 02:50
The warning is generated since there will be no content available to populate `report.conf`. Since [titles are removed by default](https://sphinxcontrib-confluencebuilder.readthedocs.io/en/latest/configuration.html#confluence-remove-title) and the `raw` directive is only targeting the `html` builder, the resulting document would have no content. This extension will not attempt to build an empty document; however a warning is still generated since the publishing event expects to publish the target document as it is part of the document set. Not an explicit warning message, but it is most likely a very low priority to address compared to other desired capabilities.

The [`raw` directive](http://docutils.sourceforge.net/docs/ref/rst/directives.html#raw-data-pass-through) is a capability which allows a power-user to directly inject non-reStructuredText data into a target document. To take advantage of this directive in this extension, the `confluence` format type can be define. For example:
```
.. raw:: confluence
    :file: my-file
```
This extension, by design of the directive type, will not manipulate any of the content provided by `my-file`. In order to be able to publish the generated document, the resulting file must be in a valid Confluence storage format (assuming one is currently using the `master` branch or prospect v1.0 (or v0.10) release when made available; otherwise v0.9 and before are still in Confluence Wiki format).

If there is a desire to directly embed HTML content into a Confluence page and the target instance supports the [HTML Macro](https://confluence.atlassian.com/doc/html-macro-38273085.html), an individual can attempt to following to include the contents of `report.html` in both HTML and Confluence based content by using the following:

```
.. raw:: confluence

   <ac:structured-macro ac:name="html">
       <ac:plain-text-body><![CDATA[

.. raw:: confluence html
    :file: generated/report.html

.. raw:: confluence

       ]]></ac:plain-text-body>
   </ac:structured-macro>
```

**Comment by Rogue-14** [comment] 2019-01-16 20:57
Thanks, that worked. I was missing the "wrapping" confluence commands with html macro.

Is there any support for sphinx _static data? I have a few javascript and css files that help make my raw html display nicer, and it doesn't appear like they are getting uploaded to confluence.

**Comment by jdknight** [comment] 2019-01-17 06:19
@Rogue-14, there is no similar capability which that [`html_static_path`](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-html_static_path) provides to Sphinx's `html` builder for this extension.

Performing custom styling and scripting calls on a Confluence instance requires administrator support (or is [out-right restricted](https://confluence.atlassian.com/confcloud/restricted-functions-in-confluence-cloud-734070955.html)). Where applicable, these capabilities can only be provided through the use of user macros and marketplace addons. If the instance being targeted does include a macro which allows styling/scripting on a page, using the `raw` directive in a similar fashion as described in the previous example would be the way to go.

**Comment by jdknight** [comment] 2019-02-27 04:24
Since this issue is over a month old and deals with no pending requests related to this extension, I will be marking this as closed as it is believed all inquires have been resolved.

**Closed by jdknight** 2019-02-27 04:24 UTC
