### ISSUE TITLE
Errors from building multiple files doesn't display which file error came from.

### ISSUE THREAD

**Issue by sabinlinden** [tonybaloney/sphinxcontrib-confluencebuilder#64] opened 2017-12-12 23:06 UTC
Less a "bug" and more of a "would be really nice to have," this issue is simply a report that, when building multiple files to send to confluence, if an error occurs, there is no traceback to see which file is causing the error.

An example of an error I'll get:

```
sphinxcontrib.confluencebuilder error:
---
An unsupported Confluence API call has been made.

REQ: PUT
RSP: 400
URL: https://lindenlab.atlassian.net/wiki/rest/api/
API: content
MSG: Error parsing xhtml: Unexpected character ''' (code 39); expected a semi-colon after the reference for entity 'deploys'
 at [row,col {unknown-source}]: [15,50]
---
```

But because I ran the sphinx-build command with -a, I have no idea which of the dozens of files I'm building is causing the error. I'm unsure if this is even something that can be fixed through the sphinxcontrib project but if it is, it'd be really helpful to have!

**Comment by jdknight** [comment] 2017-12-13 01:17
The option `-a` should not really have an effect on the publishing stage. The publishing of documents should be synchronous. So, the document in question _should_ always be the last document name listed in the `publishing...` progress status. For example. the document `sound/index` is the root cause for:
```
...
publishing... [ 50%] sound/index
sphinxcontrib.confluencebuilder error:
---
An unsupported Confluence API call has been made.
...
```
That being said, I would agree it would be more helpful to capture the document name in question as part of the exception message (in at least this exception).

**Comment by jdknight** [comment] 2018-01-05 01:55
An active PR (#73) has been made to help improve the output on a failed Confluence API error. The new change will include an output of the entire JSON data for a post/put request ~ which should include the page title and content being published (to allow easier debugging/developing). If the PR is approved/merged, I'm assuming this will cover the enhancement mentioned in this issue and will then close this issue. If this PR doesn't cover what is desired, please feel free to comment.

**Comment by jdknight** [comment] 2018-01-18 12:06
PR #73 has been merged into master and will be available next release. Marking as closed.

**Closed by jdknight** 2018-01-18 12:06 UTC
Labels: enhancement
