### ISSUE TITLE
ImportError: Must install Confluence module first to publish.

### ISSUE THREAD

**Issue by danwos** [tonybaloney/sphinxcontrib-confluencebuilder#9] opened 2017-02-09 12:09 UTC
I get the above error while trying to publish to confluence.

The error is raised because of this test in builders/confluence.py:
```python
try:
    from confluence import Confluence
    HAS_CONFLUENCE = True
except ImportError:
    HAS_CONFLUENCE = False
```
Is `confluence` here the related package from pypi? See https://pypi.python.org/pypi/confluence
I don't think so because this lib is quite old.

Maybe this is a namespace problem as you try to import something from `confluence` inside the module "confluence" (builders/confluence.py).

If it's an external lib, maybe it should be added as dependency to the setup.py file.

**Comment by danwos** [comment] 2017-02-09 12:21
Ok, reading the docs may help (arghh...).
From the README.rst:
> 'Confluence' PyPi package, 0.3.0 or later (if publishing')

But I'm not able to find such a package with this version on PyPI:
https://pypi.python.org/pypi?%3Aaction=search&term=Confluence&submit=search

Any hints?

**Comment by francobontorin** [comment] 2017-02-20 16:45
I am having the same error, these are the packages I have installed:
confluence-publisher==1.2.1
Confluence-py==1.0.1
sphinxcontrib-confluencebuilder==0.3.0

**Comment by tonybaloney** [comment] 2017-02-20 17:30
Which version of Python are you using? 




On Mon, Feb 20, 2017 at 5:45 PM +0100, "Franco Bontorin" <notifications@github.com> wrote:












I am having the same error, these are the packages I have installed:

confluence-publisher==1.2.1

Confluence-py==1.0.1

sphinxcontrib-confluencebuilder==0.3.0

**Comment by tonybaloney** [comment] 2017-02-20 18:16
This is the package

https://github.com/pycontribs/confluence

It's `confluence` with a lower case `c`.

**Comment by francobontorin** [comment] 2017-02-20 20:02
thx for your prompt response Tony, I installed this new package but still have the same error when publishing.

**Python 2.7.5**
confluence==0.1
confluence-publisher==1.2.1
Confluence-py==1.0.1
sphinxcontrib-confluencebuilder==0.3.0


$ sphinx-build -b confluence -d _build/doctrees . _build/html -E -a
Running Sphinx v1.4.5

Exception occurred:
  File "/usr/lib/python2.7/site-packages/sphinxcontrib/builders/confluence.py", line 74, in init
    raise ImportError("Must install Confluence module first to publish.")
ImportError: Must install Confluence module first to publish.

**Comment by tonybaloney** [comment] 2017-02-21 06:29
@danwos @francobontorin I've released a new version 0.4.0 . I would suggest installing it into a new virtual env using the "no site packages" flag to test it.
I've added a test to ensure that it does import correctly, but I was unable to reproduce the error after importing the correct module.
The module is now part of setup.py, so it will install it when you install the package.

**Comment by tonybaloney** [comment] 2017-02-21 06:31
I've actually just noticed that making this change that the package (`confluence`) doesn't work on Python 3.x, it raises an ImportError when importing it because of the submodule naming.
This would be a strange decoy to the original issue. Let me have a look at Python 3 support.

**Comment by danwos** [comment] 2017-03-04 10:48
This is easy to fix as the setup.py requests the outdated version 0.1:
```
requires = ['Sphinx>=1.0', 'future', 'confluence==0.1']
```
Allow newer version and it should work.
```
requires = ['Sphinx>=1.0', 'future', 'confluence>=0.1']
```

However, this plugin uses RPC and the old confluence storage format.
Are their any plans to use REST and the newer XHTML-storage format?

**Comment by jdknight** [comment] 2017-04-06 03:59
@danwos,

> Allow newer version and it should work

@tonybaloney has adjusted the `install_requires` configuration to include your proposed changes in ec30aa9a283c20ff5d43626c817004cb2e4ed47c. As for Python 3.x support, ideally the `confluence` package will get fixed in the future while XML-RPC API support is being maintained (indefinite).

> Are their any plans to use REST and the newer XHTML-storage format?

I've created [issue 16](https://github.com/tonybaloney/sphinxcontrib-confluencebuilder/issues/16) to address this enhancement request.

---

I will be marking this issue as closed as I believe the major concerns have been addressed in commits or other issues. Feel free to re-open if there is anything that was missed.

**Closed by jdknight** 2017-04-06 03:59 UTC
